/ karinamichelin$/d
/ be$/d
/ co$/d
/ rt$/d
/ twitterhandle$/d
/ rt$/d
/ tô$/d
/ ser$/d
/ ter$/d
/ haver$/d
/ né$/d
/ nao$/d
/ não$/d
/ tava$/d
/ hj$/d
/ vcs$/d
/ ai$/d
/ ja$/d
/ tu$/d
/ tbm$/d
/ eh$/d
/ k*$/d
/ que$/d
/ so$/d
/ pq$/d
/ ir$/d
/ vc$/d
/ https$/d
/ pro$/d
/ ta$/d
/ dório$/d
/ segar$/d
/ oq$/d
/ mt$/d
/ agr$/d
/ msm$/d
/ dps$/d
/ tb$/d
/ dps$/d
/ ne$/d
/ tua$/d
/ vamo$/d
/ hein$/d
/ só$/d
/ pros$/d
/ mto$/d
/ pros$/d
/ gnt$/d
/ td$/d
/ &gt$/d
/ qdo$/d
/ amg$/d
/ ngm$/d
/ mds$/d
/ ah$/d
/ vo$/d
/ qnd$/d
/ vo$/d
/ bora$/d
/ cima$/d
/ vir$/d
/ janeiro$/d
/ fevereiro$/d
/ março$/d
/ abril$/d
/ maio$/d
/ junho$/d
/ julho$/d
/ agosto$/d
/ setembro$/d
/ outubro$/d
/ novembro$/d
/ dezembro$/d
/ ok$/d
/ serrano$/d
/ ex$/d
/ rs$/d
/ emoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_e/d
/ sra$/d
/ √@emoji_copyright_e/d
/ um$/d
/ qq$/d
/ pras$/d
/ politic$/d
/ es$/d
/ as$/d
/ amp$/d
/ 100mil$/d
/ vs$/d
/ vaci$/d
/ segregará$/d
/ science$/d
/ pre$/d
/ pmc$/d
/ outro$/d
/ nada$/d
/ ling$/d
/ do$/d
/ comp$/d
/ com$/d
/ cícera$/d
/ childrenshealthdefense$/d
/ ara$/d
/ 5a$/d
/ virologyj$/d
/ @$/d
/ rolling_on_the_floor_laughing_eemoji_rolling_on_the_floor_laughing_eemoji_rolling_on_the_floor_laughing_e/d
/ qto$/d
/ qqr$/d
/ qm$/d
/ presto$/d
/ po$/d
/ p53$/d
/ nov$/d
/ n@dos$/d
/ ly$/d
/ lula$/d
/ leg$/d
/ kg$/d
/ julianaayres$/d
/ italia$/d
/ istandwithyou$/d
/ ina$/d
/ fact$/d
/ enfiem$/d
/ chzlf8jjgm$/d
/ chi$/d
/ checkers$/d
/ 3x$/d
/ a$/d
/ a$/d
/ br$/d
/ sta$/d
/ gov$/d
/ dr$/d
/ 2a$/d
/ jgikoyhj5i$/d
/ php$/d
/ stor$/d
/ story$/d
/ de$/d
/ 1a$/d
/ youtu$/d
/ uk$/d
/ 4a$/d
/ sr$/d
/ gazetabrasil$/d
/ st$/d
/ stat$/d
/ backhand_index_pointing_down_eemoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_e$/d
/ pres$/d
/ da$/d
/ sao$/d
/ se$/d
/ backhand_index_pointing_down_light_skin_tone_eemoji_backhand_index_pointing_down_light_skin_tone_eemoji_backhand_index_pointing_down_light_skin_tone_e$/d
/ backhand_index_pointing_down_eemoji_backhand_index_pointing_down_e$/d
/ 3a$/d
/ dra$/d
/ backhand_index_pointing_down_light_skin_tone_eemoji_backhand_index_pointing_down_light_skin_tone_e$/d
/ va$/d
/ tomá$/d
/ one$/d
/ no$/d
/ lion_e@selvaeaco$/d
/ jair$/d
/ police_car_light_eemoji_police_car_light_eemoji_police_car_light_e$/d
/ new$/d
/ backhand_index_pointing_down_eemoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_e$/d
/ vep6l9$/d
/ sera$/d
/ cat$/d
/ big$/d
/ min$/d
/ v@$/d
/ sé$/d
/ qquer$/d
/ medicospelavid$/d
/ a$/d
/ 3x$/d
/ vacinei$/d
/ substack$/d
/ oscasosraro$/d
/ uma$/d
/ adir$/d
/ v$/d
/ ndos$/d
/ absurdq/d
/ backhand_index_pointing_down_eemoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_eemoji_backhand_index_pointing_down_e/d
/ bion$/d
/ ehealthme$/d
/ entanto$/d
/ neto$/d
/ pas$/d
/ mo$/d
/ n$/d
/ dio$/d
/ me$/d
/ amm$/d
/ ao$/d
/ ms$/d
/ f$/d
/ t$/d
/ ewq7q7qlrp$/d
/ p$/d
/ gs$/d
/ s$/d
/ cl$/d
